[unstable]
codegen-backend = true

[alias]
cov = "tarpaulin --skip-clean --profile tarpaulin"

[profile.tarpaulin]
inherits = "dev"
debug = false

[profile.reldbg]
inherits = "dev"
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
]

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[registries.crates-io]
protocol = "sparse"
